left_arm:
  hardware_interface:
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint

right_arm:
  hardware_interface:
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
