nullvel_controller:
  type: ur_test_controllers/NullVelController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

nullvel_pid_controller:
  type: ur_test_controllers/NullVelPidController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    elbow_joint: {trajectory: 0.1, goal: 0.1}
    wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
  gains:
    shoulder_pan_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}
    shoulder_lift_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}
    elbow_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist_1_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist_2_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist_3_joint: {p: 1.0,  i: 0.0, d: 0.1, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200 # should publish at every controller update (i.e. ~125Hz)
  