nullvel_controller:
  type: ur_test_controllers/NullVelController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

nullvel_pid_controller:
  type: ur_test_controllers/NullVelPidController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200 # should publish at every controller update (i.e. ~125Hz)
  